/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as AcessoRouteImport } from './routes/acesso'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SuporteRouteImport } from './routes/suporte'
import { Route as DashboardNovaConsultaRouteImport } from './routes/_dashboard/nova-consulta'
import { Route as DashboardPainelRouteImport } from './routes/_dashboard/painel'
import { Route as DashboardRelatorioRouteImport } from './routes/_dashboard/relatorio'
import { Route as DashboardRelatoriosRouteImport } from './routes/_dashboard/relatorios'
import { Route as MarketingIndexRouteImport } from './routes/_marketing/index'
import { Route as MarketingComoFuncionaRouteImport } from './routes/_marketing/como-funciona'
import { Route as MarketingContatoRouteImport } from './routes/_marketing/contato'
import { Route as MarketingFaqRouteImport } from './routes/_marketing/faq'
import { Route as MarketingPlanosRouteImport } from './routes/_marketing/planos'
import { Route as MarketingPrivacidadeRouteImport } from './routes/_marketing/privacidade'
import { Route as MarketingPublicoRouteImport } from './routes/_marketing/publico'
import { Route as MarketingRecursosRouteImport } from './routes/_marketing/recursos'
import { Route as MarketingTermosRouteImport } from './routes/_marketing/termos'

const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const AcessoRoute = AcessoRouteImport.update({
  id: '/acesso',
  path: '/acesso',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SuporteRoute = SuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardNovaConsultaRoute = DashboardNovaConsultaRouteImport.update({
  id: '/nova-consulta',
  path: '/nova-consulta',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPainelRoute = DashboardPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRelatorioRoute = DashboardRelatorioRouteImport.update({
  id: '/relatorio',
  path: '/relatorio',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRelatoriosRoute = DashboardRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => DashboardRoute,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingComoFuncionaRoute = MarketingComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingContatoRoute = MarketingContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingFaqRoute = MarketingFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingPlanosRoute = MarketingPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingPrivacidadeRoute = MarketingPrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingPublicoRoute = MarketingPublicoRouteImport.update({
  id: '/publico',
  path: '/publico',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingRecursosRoute = MarketingRecursosRouteImport.update({
  id: '/recursos',
  path: '/recursos',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingTermosRoute = MarketingTermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => MarketingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MarketingIndexRoute
  '/acesso': typeof AcessoRoute
  '/checkout': typeof CheckoutRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/suporte': typeof SuporteRoute
  '/nova-consulta': typeof DashboardNovaConsultaRoute
  '/painel': typeof DashboardPainelRoute
  '/relatorio': typeof DashboardRelatorioRoute
  '/relatorios': typeof DashboardRelatoriosRoute
  '/como-funciona': typeof MarketingComoFuncionaRoute
  '/contato': typeof MarketingContatoRoute
  '/faq': typeof MarketingFaqRoute
  '/planos': typeof MarketingPlanosRoute
  '/privacidade': typeof MarketingPrivacidadeRoute
  '/publico': typeof MarketingPublicoRoute
  '/recursos': typeof MarketingRecursosRoute
  '/termos': typeof MarketingTermosRoute
}
export interface FileRoutesByTo {
  '/': typeof MarketingIndexRoute
  '/acesso': typeof AcessoRoute
  '/checkout': typeof CheckoutRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/suporte': typeof SuporteRoute
  '/nova-consulta': typeof DashboardNovaConsultaRoute
  '/painel': typeof DashboardPainelRoute
  '/relatorio': typeof DashboardRelatorioRoute
  '/relatorios': typeof DashboardRelatoriosRoute
  '/como-funciona': typeof MarketingComoFuncionaRoute
  '/contato': typeof MarketingContatoRoute
  '/faq': typeof MarketingFaqRoute
  '/planos': typeof MarketingPlanosRoute
  '/privacidade': typeof MarketingPrivacidadeRoute
  '/publico': typeof MarketingPublicoRoute
  '/recursos': typeof MarketingRecursosRoute
  '/termos': typeof MarketingTermosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_marketing': typeof MarketingRouteWithChildren
  '/acesso': typeof AcessoRoute
  '/checkout': typeof CheckoutRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/suporte': typeof SuporteRoute
  '/_dashboard/nova-consulta': typeof DashboardNovaConsultaRoute
  '/_dashboard/painel': typeof DashboardPainelRoute
  '/_dashboard/relatorio': typeof DashboardRelatorioRoute
  '/_dashboard/relatorios': typeof DashboardRelatoriosRoute
  '/_marketing/como-funciona': typeof MarketingComoFuncionaRoute
  '/_marketing/contato': typeof MarketingContatoRoute
  '/_marketing/faq': typeof MarketingFaqRoute
  '/_marketing/planos': typeof MarketingPlanosRoute
  '/_marketing/privacidade': typeof MarketingPrivacidadeRoute
  '/_marketing/publico': typeof MarketingPublicoRoute
  '/_marketing/recursos': typeof MarketingRecursosRoute
  '/_marketing/termos': typeof MarketingTermosRoute
  '/_marketing/': typeof MarketingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acesso'
    | '/checkout'
    | '/sitemap.xml'
    | '/suporte'
    | '/nova-consulta'
    | '/painel'
    | '/relatorio'
    | '/relatorios'
    | '/como-funciona'
    | '/contato'
    | '/faq'
    | '/planos'
    | '/privacidade'
    | '/publico'
    | '/recursos'
    | '/termos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acesso'
    | '/checkout'
    | '/sitemap.xml'
    | '/suporte'
    | '/nova-consulta'
    | '/painel'
    | '/relatorio'
    | '/relatorios'
    | '/como-funciona'
    | '/contato'
    | '/faq'
    | '/planos'
    | '/privacidade'
    | '/publico'
    | '/recursos'
    | '/termos'
  id:
    | '__root__'
    | '/_dashboard'
    | '/_marketing'
    | '/acesso'
    | '/checkout'
    | '/sitemap.xml'
    | '/suporte'
    | '/_dashboard/nova-consulta'
    | '/_dashboard/painel'
    | '/_dashboard/relatorio'
    | '/_dashboard/relatorios'
    | '/_marketing/como-funciona'
    | '/_marketing/contato'
    | '/_marketing/faq'
    | '/_marketing/planos'
    | '/_marketing/privacidade'
    | '/_marketing/publico'
    | '/_marketing/recursos'
    | '/_marketing/termos'
    | '/_marketing/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  MarketingRoute: typeof MarketingRouteWithChildren
  AcessoRoute: typeof AcessoRoute
  CheckoutRoute: typeof CheckoutRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SuporteRoute: typeof SuporteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acesso': {
      id: '/acesso'
      path: '/acesso'
      fullPath: '/acesso'
      preLoaderRoute: typeof AcessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suporte': {
      id: '/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof SuporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/nova-consulta': {
      id: '/_dashboard/nova-consulta'
      path: '/nova-consulta'
      fullPath: '/nova-consulta'
      preLoaderRoute: typeof DashboardNovaConsultaRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/painel': {
      id: '/_dashboard/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof DashboardPainelRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/relatorio': {
      id: '/_dashboard/relatorio'
      path: '/relatorio'
      fullPath: '/relatorio'
      preLoaderRoute: typeof DashboardRelatorioRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/relatorios': {
      id: '/_dashboard/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof DashboardRelatoriosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/como-funciona': {
      id: '/_marketing/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof MarketingComoFuncionaRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/contato': {
      id: '/_marketing/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof MarketingContatoRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/faq': {
      id: '/_marketing/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof MarketingFaqRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/planos': {
      id: '/_marketing/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof MarketingPlanosRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/privacidade': {
      id: '/_marketing/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof MarketingPrivacidadeRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/publico': {
      id: '/_marketing/publico'
      path: '/publico'
      fullPath: '/publico'
      preLoaderRoute: typeof MarketingPublicoRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/recursos': {
      id: '/_marketing/recursos'
      path: '/recursos'
      fullPath: '/recursos'
      preLoaderRoute: typeof MarketingRecursosRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/termos': {
      id: '/_marketing/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof MarketingTermosRouteImport
      parentRoute: typeof MarketingRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardNovaConsultaRoute: typeof DashboardNovaConsultaRoute
  DashboardPainelRoute: typeof DashboardPainelRoute
  DashboardRelatorioRoute: typeof DashboardRelatorioRoute
  DashboardRelatoriosRoute: typeof DashboardRelatoriosRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardNovaConsultaRoute: DashboardNovaConsultaRoute,
  DashboardPainelRoute: DashboardPainelRoute,
  DashboardRelatorioRoute: DashboardRelatorioRoute,
  DashboardRelatoriosRoute: DashboardRelatoriosRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface MarketingRouteChildren {
  MarketingComoFuncionaRoute: typeof MarketingComoFuncionaRoute
  MarketingContatoRoute: typeof MarketingContatoRoute
  MarketingFaqRoute: typeof MarketingFaqRoute
  MarketingPlanosRoute: typeof MarketingPlanosRoute
  MarketingPrivacidadeRoute: typeof MarketingPrivacidadeRoute
  MarketingPublicoRoute: typeof MarketingPublicoRoute
  MarketingRecursosRoute: typeof MarketingRecursosRoute
  MarketingTermosRoute: typeof MarketingTermosRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingComoFuncionaRoute: MarketingComoFuncionaRoute,
  MarketingContatoRoute: MarketingContatoRoute,
  MarketingFaqRoute: MarketingFaqRoute,
  MarketingPlanosRoute: MarketingPlanosRoute,
  MarketingPrivacidadeRoute: MarketingPrivacidadeRoute,
  MarketingPublicoRoute: MarketingPublicoRoute,
  MarketingRecursosRoute: MarketingRecursosRoute,
  MarketingTermosRoute: MarketingTermosRoute,
  MarketingIndexRoute: MarketingIndexRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  MarketingRoute: MarketingRouteWithChildren,
  AcessoRoute: AcessoRoute,
  CheckoutRoute: CheckoutRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SuporteRoute: SuporteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
